<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<Configurations>Debug;Release;NoWindowsDebug;NoWindowsRelease</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoWindowsDebug|AnyCPU'">
	  <WarningLevel>9999</WarningLevel>
	  <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoWindowsRelease|AnyCPU'">
	  <WarningLevel>9999</WarningLevel>
	  <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management.Automation" Version="7.5.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\WillPittenger.Goodies.JSON\WillPittenger.Goodies.JSON.csproj" />
	  <ProjectReference Include="..\..\WillPittenger.Goodies.Sounds\WillPittenger.Goodies.Sounds.csproj" />
	  <ProjectReference Include="..\..\WillPittenger.Goodies.Tools\WillPittenger.Goodies.Tools.csproj" />
	  <ProjectReference Include="..\..\WillPittenger.Goodies.YtDlpWrapper\WillPittenger.Goodies.YtDlpWrapper.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Rsrcs.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Rsrcs.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Rsrcs.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Rsrcs.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="WillPittenger.Goodies.PowerShell.JSON\WillPittenger.Goodies.PowerShell.JSON.psd1">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Properties\Icons\Icon 64x64.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="pwsh -NoLogo -ExecutionPolicy RemoteSigned -command &quot;&amp; {exit (. ./Post-Build.ps1 -TargetDir $(OutDir) -ProjectName $(ProjectName))}&quot;" />
	</Target>

</Project>