<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.0.0.1</Version>
    <Authors>Will Pittenger</Authors>
    <Description>A tool for calling yt-dlp from .NET code.</Description>
    <Copyright>©2025 Will Pittenger</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IncludeSymbols>True</IncludeSymbols>
    <Configurations>Debug;Release;NoWindowsDebug;NoWindowsRelease</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoWindowsDebug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoWindowsRelease|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WillPittenger.Goodies.JSON\WillPittenger.Goodies.JSON.csproj">
      <Private>True</Private>
    </ProjectReference>
    <ProjectReference Include="..\WillPittenger.Goodies.Sounds\WillPittenger.Goodies.Sounds.csproj">
      <Private>True</Private>
    </ProjectReference>
    <ProjectReference Include="..\WillPittenger.Goodies.Tools\WillPittenger.Goodies.Tools.csproj">
      <Private>True</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
