<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<NuGetAuditLevel>moderate</NuGetAuditLevel>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\WillPittenger.Goodies.Tools\WillPittenger.Goodies.Tools.csproj" />
		<PackageReference Include="System.Management.Automation" Version="7.5.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Rsrcs.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Rsrcs.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Rsrcs.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Rsrcs.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
