<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.5" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.5" />
		<PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.2.5">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>none</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Management.Automation" Version="7.5.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\..\WillPittenger.Goodies.Sounds\WillPittenger.Goodies.Sounds.csproj" />-->
		<ProjectReference Include="..\..\WillPittenger.Goodies.Tools\WillPittenger.Goodies.Tools.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="MainWnd.axaml.cs">
			<DependentUpon>MainWnd.axaml</DependentUpon>
		</Compile>
		<Compile Update="Rsrcs.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Rsrcs.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Rsrcs.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Rsrcs.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
