#
# Module manifest for module 'Org.WillPittenger.Goodies.PowerShell.Data'
#
# Generated by: Will Pittenger
#
# Generated on: 01-20-2026 8:40:33 am
#

@{
	# Script module or binary module file associated with this manifest.
	RootModule = 'WillPittenger.Goodies.PowerShell.Data.dll'

	# Version number of this module.
	ModuleVersion = '0.1.0';

	# ID used to uniquely identify this module
	GUID = '9a4b7d3e-f9b2-4500-923f-236932b3e86d';

	# Author of this module
	Author = 'Will Pittenger';

	# Company or vendor of this module
	CompanyName = '';

	# Copyright statement for this module
	Copyright = 'Copyright ©2026, . All rights reserved.';

	# Description of the functionality provided by this module
	Description = 'Provides various commands for dealing with data.  Currently, the main command retrieves metadata from files.'

	# Minimum version of the Windows PowerShell engine required by this module
	#PowerShellVersion = '5.1.19041.1682';

	# Name of the Windows PowerShell host required by this module
	#PowerShellHostName = '';

	# Minimum version of the Windows PowerShell host required by this module
	#PowerShellHostVersion = '';

	# Minimum version of the .NET Framework required by this module
	#DotNetFrameworkVersion = '9.0';

	# Minimum version of the common language runtime (CLR) required by this module
	#CLRVersion = '4.0.30319.42000';

	# Processor architecture (None, X86, Amd64) required by this module
	#ProcessorArchitecture = '';

	# Modules that must be imported into the global environment prior to importing this module
	RequiredModules = 
	@(
	);

	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies =
	@(
	);

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	#ScriptsToProcess =
	#@(
	#);

	# Type files (.ps1xml) to be loaded when importing this module
	#TypesToProcess =
	#@(
	#);

	# Format files (.ps1xml) to be loaded when importing this module
	#FormatsToProcess =
	#@(
	#);

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	NestedModules =
	@(
	);

	# Functions to export from this module
	FunctionsToExport =
	@(
	);

	# Cmdlets to export from this module
	CmdletsToExport =
	@(
		'Get-FileMetaData'
	);

	# Variables to export from this module
	VariablesToExport =
	@(
	);

	# Aliases to export from this module
	AliasesToExport =
	@(
	);

	# List of all modules packaged with this module.
	ModuleList =
	@(
	);

	# List of all files packaged with this module
	FileList = 
	@(
	);

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{
			PSData = @{
					# Tags applied to this module. These help with module discovery in online galleries.
					Tags =
					@(
						"Windows",
						"Data",
						"Metadata",
						"Files",
						"File Metadata",
						".NET"
					);

					# A URL to the license for this module.
					LicenseUri = 'https://licenses.nuget.org/LGPL-3.0-or-later';

					# A URL to the main website for this project.
					ProjectUri = 'https://github.com/WillPittenger/Goodies/tree/master/PowerShell/WillPittenger.Goodies.PowerShell.Data';

					# A URL to an icon representing this module.
					IconUri = 'https://sourceforge.net/projects/org-willpittenger-goodies-powershell-data/files/Images/Icon%2064x64.png/download';

					# ReleaseNotes of this module
					# ReleaseNotes = '';

			}; # End of PSData hashtable

	}; # End of PrivateData hashtable

	# HelpInfo URI of this module
	#HelpInfoURI = ''

	# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
	DefaultCommandPrefix = 't';
};