//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillPittenger.Goodies.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rsrcs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rsrcs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WillPittenger.Goodies.Tools.Rsrcs", typeof(Rsrcs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        internal static string strUomByte {
            get {
                return ResourceManager.GetString("strUomByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string strUomBytes {
            get {
                return ResourceManager.GetString("strUomBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string strUomBytesAbbrev {
            get {
                return ResourceManager.GetString("strUomBytesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gigabyte.
        /// </summary>
        internal static string strUomGigaByte {
            get {
                return ResourceManager.GetString("strUomGigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gigabytes.
        /// </summary>
        internal static string strUomGigaBytes {
            get {
                return ResourceManager.GetString("strUomGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gib.
        /// </summary>
        internal static string strUomGigaBytesAbbrev {
            get {
                return ResourceManager.GetString("strUomGigaBytesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gb.
        /// </summary>
        internal static string strUomGigaBytesSiAbbrev {
            get {
                return ResourceManager.GetString("strUomGigaBytesSiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilobyte.
        /// </summary>
        internal static string strUomKiloByte {
            get {
                return ResourceManager.GetString("strUomKiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilobytes.
        /// </summary>
        internal static string strUomKiloBytes {
            get {
                return ResourceManager.GetString("strUomKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kib.
        /// </summary>
        internal static string strUomKiloBytesAbbrev {
            get {
                return ResourceManager.GetString("strUomKiloBytesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kb.
        /// </summary>
        internal static string strUomKiloBytesSiAbbrev {
            get {
                return ResourceManager.GetString("strUomKiloBytesSiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megabyte.
        /// </summary>
        internal static string strUomMegaByte {
            get {
                return ResourceManager.GetString("strUomMegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megabytes.
        /// </summary>
        internal static string strUomMegaBytes {
            get {
                return ResourceManager.GetString("strUomMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mib.
        /// </summary>
        internal static string strUomMegaBytesAbbrev {
            get {
                return ResourceManager.GetString("strUomMegaBytesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mb.
        /// </summary>
        internal static string strUomMegaBytesSiAbbrev {
            get {
                return ResourceManager.GetString("strUomMegaBytesSiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terabyte.
        /// </summary>
        internal static string strUomTeraByte {
            get {
                return ResourceManager.GetString("strUomTeraByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terabytes.
        /// </summary>
        internal static string strUomTeraBytes {
            get {
                return ResourceManager.GetString("strUomTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tib.
        /// </summary>
        internal static string strUomTeraBytesAbbrev {
            get {
                return ResourceManager.GetString("strUomTeraBytesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tb.
        /// </summary>
        internal static string strUomTeraBytesSiAbbrev {
            get {
                return ResourceManager.GetString("strUomTeraBytesSiAbbrev", resourceCulture);
            }
        }
    }
}
