<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>Will Pittenger</Authors>
		<Version>0.1.0</Version>
		<Copyright>©Will Pittenger 2026</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<PackageProjectUrl>https://github.com/WillPittenger/Goodies/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/WillPittenger/Goodies/tree/master/PowerShell/WillPittenger.Goodies.PowerShell.Data</RepositoryUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageTags>Windows;Data;Metadata;Files;File Metadata;.NET</PackageTags>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<Title>Data goodies for PowerShell</Title>
		<Description>Set of CmdLets for PowerShell related to Data.</Description>
		<Configurations>Debug;Release</Configurations>
		<WarningsAsErrors>$(WarningsAsErrors);NU1605;CS8618;CA2021;CS8524;CS8509;CS0108;CS0114;CS8604;CS8603</WarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management.Automation" Version="7.5.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\WillPittenger.Goodies.Data\WillPittenger.Goodies.Data.csproj" />
	  <ProjectReference Include="..\..\WillPittenger.Goodies.Tools\WillPittenger.Goodies.Tools.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="readme.md">
		  <PackagePath>\</PackagePath>
		  <Pack>True</Pack>
		</None>
		<None Update="WillPittenger.Goodies.PowerShell.Data\WillPittenger.Goodies.PowerShell.Data.psd1">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Properties\Icons\Icon 64x64.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="WillPittenger.Goodies.PowerShell.Data\WillPittenger.Goodies.PowerShell.Data.psd1">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="pwsh -NoLogo -ExecutionPolicy RemoteSigned -command &quot;&amp; {exit (. ./Post-Build.ps1 -TargetDir $(OutDir) -ProjectName $(ProjectName))}&quot;" />
	</Target>

</Project>