// Ignore Spelling: BSTR

namespace Windows.Win32.Foundation;

/// <summary>
/// The rest of <see cref="BSTR"/> was generated by CsWin32.  However, <see cref="WillPittenger.Goodies.PowerShell.YtDlpWrapper"/> needs the ability to get a <see cref="BSTR"/> from a <see cref="string"/>.  So a static constructor was added here along with a typecast operator.
/// </summary>
unsafe partial struct BSTR : System.IDisposable
{
	/// <summary>
	/// Constructs a new <see cref="BSTR"/> from a <see cref="string"/>.
	/// </summary>
	/// <param name="strConvertThis">The string to convert</param>
	public BSTR(in string strConvertThis)
		=> Value = (char*)System.Runtime.InteropServices.Marshal.StringToBSTR(strConvertThis);


	/// <summary>
	/// Disposes of this <see cref="BSTR"/> when the scope of the <see langword="using"/> ends.
	/// </summary>
	public void Dispose()
		=> System.Runtime.InteropServices.Marshal.FreeBSTR((nint)Value);


	/// <summary>
	/// Convenient way to construct a <see cref="BSTR"/> from a <see cref="string"/>.  This matches the other typecast operators in <see cref="BSTR"/>.
	/// </summary>
	/// <param name="strWhatToConvert"></param>
	public static implicit operator BSTR(in string strWhatToConvert)
		=> new(strWhatToConvert);

	/// <summary>
	/// Returns a <see cref="string"/> for a given <see cref="BSTR"/>.
	/// </summary>
	/// <param name="bstrConvertThis"></param>
	public static explicit operator string(in BSTR bstrConvertThis)
		=> System.Runtime.InteropServices.Marshal.PtrToStringBSTR((nint)bstrConvertThis.Value);
}